---

- name: "Ensure bzip2 package is installed"
  package:
    name: bzip2
    state: present

- name: "Prepare temporary file for download"
  tempfile: state=file
  register: tmpfile

- name: "Download teamspeak {{ teamspeak.version }} server files"
  get_url:
    url: "http://dl.4players.de/ts/releases/{{ teamspeak.version }}/teamspeak3-server_linux_amd64-{{ teamspeak.version }}.tar.bz2"
    dest: "{{ tmpfile.path }}"
    checksum: "{{ teamspeak.checksum }}"

- name: "Install teamspeak server files"
  unarchive:
    src: "{{ tmpfile.path }}"
    remote_src: yes
    dest: "{{ teamspeak.home }}"
    owner: "{{ teamspeak.user }}"
    group: "{{ teamspeak.user }}"
    extra_opts: [--strip-components=1]
  notify:
    - Restart teamspeak server

- name: "Cleanup temporary download file"
  file:
    state: absent
    path: "{{ tmpfile.path }}"

- name: "Create VERSION file"
  copy:
    content: "{{ teamspeak.version }}"
    dest: "{{ teamspeak.home }}/VERSION"
    mode: 0600
    owner: "{{ teamspeak.user }}"
    group: "{{ teamspeak.user }}"
